name: myapp

on:
  push:

jobs:
  secondjob:
    runs-on: ubuntu-latest

    steps:
      - name: welcome message
        run: echo "welcome to gitaction"

      - name: list
        run: ls

      - name: read file
        run: cat README.md